POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "admin2",
    "responsability": "viewer",
    "email": "admin@admin",
    "password": "1234"
}

### Защищенный роут
GET http://localhost:3000/api/get-item-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJhZG1pbjIiLCJsb2dpbiI6ImFkbWluQGFkbWluIiwiaWF0IjoxNjAxNjUyOTA5LCJleHAiOjE2MDE2NTI5Mzl9.8dhKxFiwtyZFKED-JdElKs3rgsiDYIw95kHzXiXgoak

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "admin@admin",
    "password": "1234"
}

###
POST http://localhost:3000/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJhZG1pbjIiLCJsb2dpbiI6ImFkbWluQGFkbWluIiwiaWF0IjoxNjAxNjUyOTA5LCJleHAiOjE2MzMyMTA1MDl9.JPDLDWpuFv07RQ7vReKXUT4vfKTPats7A6mO0ZfNyMk"
}