POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "admin2",
    "responsability": "viewer",
    "email": "admin@admin",
    "password": "1234"
}

### Защищенный роут
GET http://localhost:3000/api/get-item-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJhZG1pbjIiLCJsb2dpbiI6ImFkbWluQGFkbWluIiwiaWF0IjoxNjAyNjAxMDY1LCJleHAiOjE2MDI2MDEwOTV9.Cxn1949wS6hLsI08lprOJ38D8lwJGenDBQLo9RpCDRw

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "admin@admin",
    "password": "1234"
}

###
POST http://localhost:3000/api/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJhZG1pbjIiLCJsb2dpbiI6ImFkbWluQGFkbWluIiwiaWF0IjoxNjAyNjAwOTk1LCJleHAiOjE2MzQxNTg1OTV9.5RdL41zHfpHgzTFIb9haULFjxgpPL1cvp3Sy-r6M4vw"
}